version: '2.2'
services:
  web:
    container_name: web
    image: api:latest
    ports:
      - 80:80
      - 443:443
nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    links:
        - web
