version: '3'
services: 
  api:
    image: api:latest
    container_name: api
    ports:
      - 8901:8901    
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27100:27017
 
