version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: stage_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/sites-available/dev.gignox.com.conf
    ports:
      - 80:80
      - 443:443
    links:
        - api    
  api:
    image: api:latest
    container_name: api
    ports:
      - 8903:8903    


