// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gigxRR.proto

package gigxRR

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//#Database modal structs
type User struct {
	Id                             string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                           string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname                        string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                          string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username                       string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password                       string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Description                    string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ImagePath                      string   `protobuf:"bytes,8,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	TotalSpace                     int32    `protobuf:"varint,9,opt,name=total_space,json=totalSpace,proto3" json:"total_space,omitempty"`
	CreatedDate                    string   `protobuf:"bytes,10,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate                    string   `protobuf:"bytes,11,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	LanguageType                   string   `protobuf:"bytes,12,opt,name=language_type,json=languageType,proto3" json:"language_type,omitempty"`
	IsMailSuccess                  string   `protobuf:"bytes,13,opt,name=is_mail_success,json=isMailSuccess,proto3" json:"is_mail_success,omitempty"`
	LoginAttempt                   int32    `protobuf:"varint,14,opt,name=login_attempt,json=loginAttempt,proto3" json:"login_attempt,omitempty"`
	RegisterVerificationCode       string   `protobuf:"bytes,15,opt,name=register_verification_code,json=registerVerificationCode,proto3" json:"register_verification_code,omitempty"`
	ForgotPasswordVerificationCode string   `protobuf:"bytes,16,opt,name=forgot_password_verification_code,json=forgotPasswordVerificationCode,proto3" json:"forgot_password_verification_code,omitempty"`
	IsRecaptchaOn                  bool     `protobuf:"varint,17,opt,name=is_recaptcha_on,json=isRecaptchaOn,proto3" json:"is_recaptcha_on,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *User) GetTotalSpace() int32 {
	if m != nil {
		return m.TotalSpace
	}
	return 0
}

func (m *User) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *User) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *User) GetLanguageType() string {
	if m != nil {
		return m.LanguageType
	}
	return ""
}

func (m *User) GetIsMailSuccess() string {
	if m != nil {
		return m.IsMailSuccess
	}
	return ""
}

func (m *User) GetLoginAttempt() int32 {
	if m != nil {
		return m.LoginAttempt
	}
	return 0
}

func (m *User) GetRegisterVerificationCode() string {
	if m != nil {
		return m.RegisterVerificationCode
	}
	return ""
}

func (m *User) GetForgotPasswordVerificationCode() string {
	if m != nil {
		return m.ForgotPasswordVerificationCode
	}
	return ""
}

func (m *User) GetIsRecaptchaOn() bool {
	if m != nil {
		return m.IsRecaptchaOn
	}
	return false
}

type Follow struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowerId           string   `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowedId           string   `protobuf:"bytes,3,opt,name=followed_id,json=followedId,proto3" json:"followed_id,omitempty"`
	FollowDate           string   `protobuf:"bytes,4,opt,name=follow_date,json=followDate,proto3" json:"follow_date,omitempty"`
	UnfollowDate         string   `protobuf:"bytes,5,opt,name=unfollow_date,json=unfollowDate,proto3" json:"unfollow_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Follow) Reset()         { *m = Follow{} }
func (m *Follow) String() string { return proto.CompactTextString(m) }
func (*Follow) ProtoMessage()    {}
func (*Follow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{1}
}

func (m *Follow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Follow.Unmarshal(m, b)
}
func (m *Follow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Follow.Marshal(b, m, deterministic)
}
func (m *Follow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Follow.Merge(m, src)
}
func (m *Follow) XXX_Size() int {
	return xxx_messageInfo_Follow.Size(m)
}
func (m *Follow) XXX_DiscardUnknown() {
	xxx_messageInfo_Follow.DiscardUnknown(m)
}

var xxx_messageInfo_Follow proto.InternalMessageInfo

func (m *Follow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Follow) GetFollowerId() string {
	if m != nil {
		return m.FollowerId
	}
	return ""
}

func (m *Follow) GetFollowedId() string {
	if m != nil {
		return m.FollowedId
	}
	return ""
}

func (m *Follow) GetFollowDate() string {
	if m != nil {
		return m.FollowDate
	}
	return ""
}

func (m *Follow) GetUnfollowDate() string {
	if m != nil {
		return m.UnfollowDate
	}
	return ""
}

type Folder struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedDate          string   `protobuf:"bytes,4,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Folder) Reset()         { *m = Folder{} }
func (m *Folder) String() string { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()    {}
func (*Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{2}
}

func (m *Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Folder.Unmarshal(m, b)
}
func (m *Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Folder.Marshal(b, m, deterministic)
}
func (m *Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Folder.Merge(m, src)
}
func (m *Folder) XXX_Size() int {
	return xxx_messageInfo_Folder.Size(m)
}
func (m *Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_Folder.DiscardUnknown(m)
}

var xxx_messageInfo_Folder proto.InternalMessageInfo

func (m *Folder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Folder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Folder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Folder) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Folder) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId             string   `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedDate          string   `protobuf:"bytes,6,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,7,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	FileHash             string   `protobuf:"bytes,8,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	IsBuried             bool     `protobuf:"varint,9,opt,name=is_buried,json=isBuried,proto3" json:"is_buried,omitempty"`
	IsFolderFile         bool     `protobuf:"varint,10,opt,name=is_folder_file,json=isFolderFile,proto3" json:"is_folder_file,omitempty"`
	IsStarred            bool     `protobuf:"varint,11,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	IsTrash              bool     `protobuf:"varint,12,opt,name=is_trash,json=isTrash,proto3" json:"is_trash,omitempty"`
	IsDeleted            bool     `protobuf:"varint,13,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *File) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *File) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *File) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *File) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *File) GetIsBuried() bool {
	if m != nil {
		return m.IsBuried
	}
	return false
}

func (m *File) GetIsFolderFile() bool {
	if m != nil {
		return m.IsFolderFile
	}
	return false
}

func (m *File) GetIsStarred() bool {
	if m != nil {
		return m.IsStarred
	}
	return false
}

func (m *File) GetIsTrash() bool {
	if m != nil {
		return m.IsTrash
	}
	return false
}

func (m *File) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Buried struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileHash             string   `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	PublicHash           string   `protobuf:"bytes,5,opt,name=public_hash,json=publicHash,proto3" json:"public_hash,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	BuriedDate           string   `protobuf:"bytes,7,opt,name=buried_date,json=buriedDate,proto3" json:"buried_date,omitempty"`
	DiggingDate          string   `protobuf:"bytes,8,opt,name=digging_date,json=diggingDate,proto3" json:"digging_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buried) Reset()         { *m = Buried{} }
func (m *Buried) String() string { return proto.CompactTextString(m) }
func (*Buried) ProtoMessage()    {}
func (*Buried) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{4}
}

func (m *Buried) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buried.Unmarshal(m, b)
}
func (m *Buried) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buried.Marshal(b, m, deterministic)
}
func (m *Buried) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buried.Merge(m, src)
}
func (m *Buried) XXX_Size() int {
	return xxx_messageInfo_Buried.Size(m)
}
func (m *Buried) XXX_DiscardUnknown() {
	xxx_messageInfo_Buried.DiscardUnknown(m)
}

var xxx_messageInfo_Buried proto.InternalMessageInfo

func (m *Buried) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Buried) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Buried) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Buried) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Buried) GetPublicHash() string {
	if m != nil {
		return m.PublicHash
	}
	return ""
}

func (m *Buried) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Buried) GetBuriedDate() string {
	if m != nil {
		return m.BuriedDate
	}
	return ""
}

func (m *Buried) GetDiggingDate() string {
	if m != nil {
		return m.DiggingDate
	}
	return ""
}

//Check is service working ?
type HelloRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{5}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{6}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//Only for use login
type UserLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{7}
}

func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (m *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(m, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//User methods start
type RegisterUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{8}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{9}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserRequest struct {
	User                 *UserLogin `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{10}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUser() *UserLogin {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserResponse struct {
	User                 *UserLogin `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{11}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *UserLogin {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{12}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{13}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{14}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{15}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//User methods finish
type UpdateFileRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{16}
}

func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(m, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type UpdateFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileResponse) Reset()         { *m = UpdateFileResponse{} }
func (m *UpdateFileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFileResponse) ProtoMessage()    {}
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{17}
}

func (m *UpdateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileResponse.Unmarshal(m, b)
}
func (m *UpdateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileResponse.Merge(m, src)
}
func (m *UpdateFileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFileResponse.Size(m)
}
func (m *UpdateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileResponse proto.InternalMessageInfo

func (m *UpdateFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{18}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *GetFileRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type GetFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{19}
}

func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (m *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(m, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetAllFilesRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFilesRequest) Reset()         { *m = GetAllFilesRequest{} }
func (m *GetAllFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllFilesRequest) ProtoMessage()    {}
func (*GetAllFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{20}
}

func (m *GetAllFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFilesRequest.Unmarshal(m, b)
}
func (m *GetAllFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFilesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFilesRequest.Merge(m, src)
}
func (m *GetAllFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllFilesRequest.Size(m)
}
func (m *GetAllFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFilesRequest proto.InternalMessageInfo

func (m *GetAllFilesRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetAllFilesResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFilesResponse) Reset()         { *m = GetAllFilesResponse{} }
func (m *GetAllFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllFilesResponse) ProtoMessage()    {}
func (*GetAllFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{21}
}

func (m *GetAllFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFilesResponse.Unmarshal(m, b)
}
func (m *GetAllFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFilesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFilesResponse.Merge(m, src)
}
func (m *GetAllFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllFilesResponse.Size(m)
}
func (m *GetAllFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFilesResponse proto.InternalMessageInfo

func (m *GetAllFilesResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type DeleteFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{22}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *DeleteFileRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type DeleteFileResponse struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{23}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *DeleteFileResponse) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "gigx.User")
	proto.RegisterType((*Follow)(nil), "gigx.Follow")
	proto.RegisterType((*Folder)(nil), "gigx.Folder")
	proto.RegisterType((*File)(nil), "gigx.File")
	proto.RegisterType((*Buried)(nil), "gigx.Buried")
	proto.RegisterType((*HelloRequest)(nil), "gigx.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "gigx.HelloResponse")
	proto.RegisterType((*UserLogin)(nil), "gigx.UserLogin")
	proto.RegisterType((*RegisterUserRequest)(nil), "gigx.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "gigx.RegisterUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "gigx.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "gigx.LoginUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "gigx.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "gigx.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "gigx.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "gigx.DeleteUserResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "gigx.UpdateFileRequest")
	proto.RegisterType((*UpdateFileResponse)(nil), "gigx.UpdateFileResponse")
	proto.RegisterType((*GetFileRequest)(nil), "gigx.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "gigx.GetFileResponse")
	proto.RegisterType((*GetAllFilesRequest)(nil), "gigx.GetAllFilesRequest")
	proto.RegisterType((*GetAllFilesResponse)(nil), "gigx.GetAllFilesResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "gigx.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "gigx.DeleteFileResponse")
}

func init() { proto.RegisterFile("proto/gigxRR.proto", fileDescriptor_9ce114fac961b177) }

var fileDescriptor_9ce114fac961b177 = []byte{
	// 1094 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0x6e, 0xbc, 0xbb, 0xde, 0xb3, 0x9b, 0xa4, 0x99, 0x04, 0xe2, 0x2c, 0xa2, 0x49, 0x5d,
	0x84, 0x82, 0x04, 0x01, 0x9a, 0xb6, 0xf4, 0x02, 0x09, 0xa5, 0x44, 0x49, 0x83, 0xf8, 0xa9, 0x9c,
	0x16, 0x09, 0x6e, 0xac, 0x89, 0x3d, 0x71, 0x46, 0x38, 0xb6, 0xf1, 0xcc, 0xb6, 0xe4, 0x92, 0x6b,
	0x5e, 0x82, 0x77, 0xe1, 0x39, 0x78, 0x09, 0x9e, 0x00, 0xcd, 0x99, 0x71, 0x3c, 0x5e, 0x2f, 0xc9,
	0x96, 0xde, 0xe5, 0x7c, 0xe7, 0x3b, 0x3f, 0xdf, 0xcc, 0x39, 0xe3, 0x2c, 0x90, 0xa2, 0xcc, 0x65,
	0xfe, 0x69, 0xc2, 0x93, 0xdf, 0x82, 0x60, 0x0f, 0x0d, 0xe2, 0x28, 0xcb, 0xff, 0xdb, 0x01, 0xe7,
	0xa5, 0x60, 0x25, 0x59, 0x81, 0x2e, 0x8f, 0xbd, 0xce, 0x4e, 0x67, 0x77, 0x18, 0x74, 0x79, 0x4c,
	0x08, 0x38, 0x19, 0xbd, 0x64, 0x5e, 0x17, 0x11, 0xfc, 0x9b, 0x78, 0x30, 0x10, 0xd3, 0x12, 0xe1,
	0x25, 0x84, 0x2b, 0x93, 0x6c, 0x40, 0x8f, 0x5d, 0x52, 0x9e, 0x7a, 0x0e, 0xe2, 0xda, 0x20, 0x13,
	0x70, 0xa7, 0x82, 0xe9, 0x80, 0x1e, 0x3a, 0xae, 0x6d, 0xe5, 0x2b, 0xa8, 0x10, 0xaf, 0xf3, 0x32,
	0xf6, 0xfa, 0xda, 0x57, 0xd9, 0x64, 0x07, 0x46, 0x31, 0x13, 0x51, 0xc9, 0x0b, 0xc9, 0xf3, 0xcc,
	0x1b, 0xa0, 0xdb, 0x86, 0xc8, 0xfb, 0x00, 0xfc, 0x92, 0x26, 0x2c, 0x2c, 0xa8, 0xbc, 0xf0, 0x5c,
	0x24, 0x0c, 0x11, 0x79, 0x4e, 0xe5, 0x05, 0xd9, 0x86, 0x91, 0xcc, 0x25, 0x4d, 0x43, 0x51, 0xd0,
	0x88, 0x79, 0xc3, 0x9d, 0xce, 0x6e, 0x2f, 0x00, 0x84, 0x4e, 0x15, 0x42, 0xee, 0xc1, 0x38, 0x2a,
	0x19, 0x95, 0x2c, 0x0e, 0x63, 0x2a, 0x99, 0x07, 0xba, 0x84, 0xc1, 0x0e, 0xa9, 0x44, 0xca, 0xb4,
	0x88, 0x6b, 0xca, 0x48, 0x53, 0x0c, 0x86, 0x94, 0xfb, 0xb0, 0x9c, 0xd2, 0x2c, 0x99, 0xaa, 0x46,
	0xe4, 0x55, 0xc1, 0xbc, 0x31, 0x72, 0xc6, 0x15, 0xf8, 0xe2, 0xaa, 0x60, 0xe4, 0x43, 0x58, 0xe5,
	0x22, 0x54, 0xe7, 0x11, 0x8a, 0x69, 0x14, 0x31, 0x21, 0xbc, 0x65, 0xa4, 0x2d, 0x73, 0xf1, 0x1d,
	0xe5, 0xe9, 0xa9, 0x06, 0x31, 0x59, 0x9e, 0xf0, 0x2c, 0xa4, 0x52, 0xb2, 0xcb, 0x42, 0x7a, 0x2b,
	0xd8, 0xf5, 0x18, 0xc1, 0x03, 0x8d, 0x91, 0x2f, 0x61, 0x52, 0xb2, 0x84, 0x0b, 0xc9, 0xca, 0xf0,
	0x15, 0x2b, 0xf9, 0x39, 0x8f, 0xa8, 0x3a, 0x90, 0x30, 0xca, 0x63, 0xe6, 0xad, 0x62, 0x5e, 0xaf,
	0x62, 0xfc, 0x68, 0x11, 0xbe, 0xce, 0x63, 0x46, 0x4e, 0xe0, 0xde, 0x79, 0x5e, 0x26, 0xb9, 0x0c,
	0xab, 0xa3, 0x9e, 0x93, 0xe4, 0x0e, 0x26, 0xb9, 0xab, 0x89, 0xcf, 0x0d, 0xaf, 0x95, 0x4a, 0xab,
	0x2a, 0x59, 0x44, 0x0b, 0x19, 0x5d, 0xd0, 0x30, 0xcf, 0xbc, 0xb5, 0x9d, 0xce, 0xae, 0xab, 0x54,
	0x05, 0x15, 0xfa, 0x43, 0xe6, 0xff, 0xd9, 0x81, 0xfe, 0x51, 0x9e, 0xa6, 0xf9, 0xeb, 0xd6, 0x84,
	0x6d, 0xc3, 0xe8, 0x1c, 0x3d, 0xac, 0x0c, 0x79, 0x6c, 0x06, 0x0d, 0x2a, 0xe8, 0xc4, 0x26, 0xc4,
	0x8a, 0xb0, 0xd4, 0x20, 0xc4, 0x36, 0x41, 0xdf, 0x90, 0x63, 0x13, 0xaa, 0x0b, 0x9a, 0x66, 0x36,
	0x45, 0x4f, 0xe1, 0xb8, 0x02, 0x15, 0xc9, 0xff, 0x43, 0xb7, 0x18, 0x2f, 0xb8, 0x04, 0x9b, 0x30,
	0x50, 0x43, 0x5c, 0x77, 0xd4, 0x57, 0xe6, 0x49, 0xdc, 0x9a, 0x29, 0xe7, 0xf6, 0x99, 0xea, 0xb5,
	0x66, 0xca, 0xff, 0x7d, 0x09, 0x9c, 0x23, 0x9e, 0xb2, 0x56, 0x2f, 0x56, 0xdd, 0x6e, 0xa3, 0xee,
	0x7b, 0x30, 0x3c, 0xc7, 0xf6, 0xeb, 0x96, 0x5c, 0x0d, 0x9c, 0xd4, 0x0a, 0x1c, 0x4b, 0xc1, 0xcc,
	0x7a, 0xf5, 0xda, 0xeb, 0x35, 0x2b, 0xa5, 0x7f, 0xbb, 0x94, 0x41, 0x7b, 0x3d, 0x54, 0x63, 0x3c,
	0x65, 0xe1, 0x05, 0x15, 0xd5, 0x8e, 0xba, 0x0a, 0x78, 0x46, 0xc5, 0x85, 0x72, 0x72, 0x11, 0x9e,
	0x4d, 0x4b, 0xce, 0x62, 0x5c, 0x50, 0x37, 0x70, 0xb9, 0x78, 0x8a, 0x36, 0xf9, 0x00, 0x56, 0xb8,
	0x08, 0x8d, 0x2a, 0x15, 0x82, 0x0b, 0xea, 0x06, 0x63, 0x2e, 0xf4, 0x4d, 0xe1, 0x09, 0xa9, 0x47,
	0x40, 0x84, 0x42, 0xd2, 0xb2, 0x64, 0x31, 0xee, 0xa7, 0x1b, 0x0c, 0xb9, 0x38, 0xd5, 0x00, 0xd9,
	0x02, 0x97, 0x8b, 0x50, 0x96, 0xaa, 0xfa, 0x18, 0x9d, 0x03, 0x2e, 0x5e, 0x28, 0xd3, 0x44, 0xc6,
	0x2c, 0x65, 0x92, 0xc5, 0xb8, 0x8e, 0x18, 0x79, 0xa8, 0x01, 0xff, 0x9f, 0x0e, 0xf4, 0x4d, 0x27,
	0x6f, 0x74, 0x0b, 0x4a, 0xac, 0xf5, 0x3a, 0xa2, 0xd8, 0xef, 0xd5, 0x89, 0x37, 0x4e, 0xc2, 0x99,
	0x39, 0x89, 0x6d, 0x18, 0x15, 0xd3, 0xb3, 0x94, 0x47, 0xda, 0xad, 0xaf, 0x03, 0x34, 0x84, 0x84,
	0x99, 0xfb, 0xea, 0xb7, 0xef, 0x6b, 0x1b, 0x46, 0xfa, 0x24, 0xed, 0xbb, 0x00, 0x0d, 0x55, 0xb7,
	0x15, 0xf3, 0x24, 0xe1, 0x59, 0xa2, 0x19, 0xae, 0xc9, 0xa1, 0x31, 0x1c, 0xbc, 0x5d, 0x18, 0x3f,
	0x63, 0x69, 0x9a, 0x07, 0xec, 0xd7, 0x29, 0x13, 0x52, 0x3d, 0xf6, 0x97, 0x4c, 0x08, 0x9a, 0x30,
	0x23, 0xbf, 0x32, 0xfd, 0x8f, 0x60, 0xd9, 0x30, 0x45, 0x91, 0x67, 0x82, 0xdd, 0x40, 0xfd, 0x09,
	0x86, 0xea, 0xeb, 0xf2, 0xad, 0x7a, 0xc3, 0x1a, 0x9f, 0x83, 0xce, 0x0d, 0x9f, 0x83, 0xee, 0xcc,
	0xe7, 0x60, 0x03, 0x7a, 0x32, 0xff, 0x85, 0x65, 0xe6, 0x58, 0xb5, 0xe1, 0x3f, 0x82, 0xf5, 0xc0,
	0x3c, 0x74, 0xaa, 0x44, 0xd5, 0xf6, 0x5d, 0x70, 0x54, 0x52, 0x2c, 0x30, 0x7a, 0x00, 0x7b, 0xea,
	0x2b, 0xb7, 0x87, 0x04, 0xc4, 0xfd, 0xc7, 0xb0, 0xd1, 0x0c, 0x33, 0x1a, 0x6e, 0x8b, 0xfb, 0x02,
	0xee, 0xa0, 0x0a, 0xbb, 0xd6, 0xfd, 0x46, 0xcc, 0x6a, 0x1d, 0x83, 0x4c, 0x13, 0xf8, 0x04, 0xd6,
	0xac, 0x40, 0x53, 0x6d, 0xa1, 0xc8, 0x7d, 0x58, 0x7b, 0x89, 0xeb, 0xf4, 0x26, 0xfa, 0x1e, 0x02,
	0xb1, 0x83, 0x16, 0x54, 0xf7, 0x31, 0xac, 0xe9, 0xe1, 0xb7, 0x4b, 0x59, 0xb3, 0xde, 0xb1, 0x67,
	0xdd, 0xff, 0x04, 0x88, 0xcd, 0x36, 0x35, 0xfe, 0x93, 0x7e, 0xad, 0x43, 0x6d, 0xad, 0xa5, 0x03,
	0x17, 0xbb, 0xd1, 0x11, 0x12, 0x10, 0xaf, 0x75, 0xe8, 0xa0, 0x5a, 0xc7, 0x8d, 0x51, 0x47, 0xb0,
	0x72, 0xcc, 0xa4, 0x5d, 0x67, 0x13, 0x06, 0xb8, 0x7a, 0x75, 0x57, 0xca, 0xb4, 0x16, 0x16, 0x97,
	0xae, 0xdb, 0xdc, 0x49, 0xff, 0x73, 0x58, 0xbd, 0xce, 0xb3, 0x60, 0xe9, 0x87, 0x40, 0x8e, 0x99,
	0x3c, 0x48, 0x53, 0x85, 0x89, 0x45, 0x65, 0x3e, 0x82, 0xf5, 0x46, 0xd4, 0x82, 0xc5, 0x4e, 0xaa,
	0xfb, 0x7a, 0x7b, 0xa9, 0xdf, 0x54, 0x97, 0xd9, 0x50, 0xfb, 0xbf, 0x72, 0x3d, 0xf8, 0xcb, 0x81,
	0xe5, 0x63, 0xfc, 0x27, 0xf3, 0x94, 0x95, 0xaf, 0x78, 0xc4, 0xc8, 0x3e, 0xb8, 0xa7, 0xf4, 0x0a,
	0x9f, 0x0b, 0x42, 0xb4, 0x0c, 0xfb, 0x95, 0x99, 0xac, 0x37, 0x30, 0x53, 0xfc, 0x09, 0xf4, 0xf4,
	0x8b, 0xf1, 0xae, 0xf6, 0xce, 0x2e, 0xde, 0x64, 0xb3, 0x85, 0x9b, 0xc8, 0x03, 0x70, 0xab, 0xed,
	0x26, 0x5b, 0x9a, 0x34, 0xe7, 0x91, 0x98, 0x4c, 0xe6, 0xb9, 0x4c, 0x8a, 0xaf, 0x00, 0xea, 0x05,
	0x22, 0xa6, 0x52, 0x6b, 0x0f, 0x27, 0x5e, 0xdb, 0x51, 0x27, 0xa8, 0xb7, 0xa3, 0x4a, 0xd0, 0xda,
	0xae, 0x2a, 0xc1, 0x9c, 0x45, 0x7a, 0x0c, 0x03, 0x33, 0x7c, 0x64, 0x43, 0x93, 0x9a, 0x33, 0x3d,
	0x79, 0x67, 0x06, 0x35, 0x71, 0x87, 0x30, 0xb2, 0x66, 0x89, 0x78, 0xd7, 0xac, 0x99, 0xa1, 0x9c,
	0x6c, 0xcd, 0xf1, 0xe8, 0x1c, 0x9f, 0x75, 0x6a, 0xfd, 0xd8, 0x40, 0x43, 0xbf, 0xdd, 0x83, 0xd7,
	0x76, 0xcc, 0xea, 0xb7, 0x13, 0xb4, 0xa6, 0xb5, 0xa9, 0xdf, 0x4e, 0xf0, 0xd4, 0xfd, 0xb9, 0xaf,
	0x7f, 0xa9, 0x9c, 0xf5, 0xf1, 0xa7, 0xca, 0xfe, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xff,
	0x1b, 0xf1, 0xc0, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GigxRRServiceClient is the client API for GigxRRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GigxRRServiceClient interface {
	//Check service
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	//User methods
	Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	//File methods
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetAllFiles(ctx context.Context, in *GetAllFilesRequest, opts ...grpc.CallOption) (GigxRRService_GetAllFilesClient, error)
	UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type gigxRRServiceClient struct {
	cc *grpc.ClientConn
}

func NewGigxRRServiceClient(cc *grpc.ClientConn) GigxRRServiceClient {
	return &gigxRRServiceClient{cc}
}

func (c *gigxRRServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) GetAllFiles(ctx context.Context, in *GetAllFilesRequest, opts ...grpc.CallOption) (GigxRRService_GetAllFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GigxRRService_serviceDesc.Streams[0], "/gigx.GigxRRService/GetAllFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &gigxRRServiceGetAllFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GigxRRService_GetAllFilesClient interface {
	Recv() (*GetAllFilesResponse, error)
	grpc.ClientStream
}

type gigxRRServiceGetAllFilesClient struct {
	grpc.ClientStream
}

func (x *gigxRRServiceGetAllFilesClient) Recv() (*GetAllFilesResponse, error) {
	m := new(GetAllFilesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gigxRRServiceClient) UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error) {
	out := new(UpdateFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/UpdateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GigxRRServiceServer is the server API for GigxRRService service.
type GigxRRServiceServer interface {
	//Check service
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	//User methods
	Login(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	//File methods
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetAllFiles(*GetAllFilesRequest, GigxRRService_GetAllFilesServer) error
	UpdateFile(context.Context, *UpdateFileRequest) (*UpdateFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
}

func RegisterGigxRRServiceServer(s *grpc.Server, srv GigxRRServiceServer) {
	s.RegisterService(&_GigxRRService_serviceDesc, srv)
}

func _GigxRRService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).Login(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_GetAllFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GigxRRServiceServer).GetAllFiles(m, &gigxRRServiceGetAllFilesServer{stream})
}

type GigxRRService_GetAllFilesServer interface {
	Send(*GetAllFilesResponse) error
	grpc.ServerStream
}

type gigxRRServiceGetAllFilesServer struct {
	grpc.ServerStream
}

func (x *gigxRRServiceGetAllFilesServer) Send(m *GetAllFilesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GigxRRService_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/UpdateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).UpdateFile(ctx, req.(*UpdateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GigxRRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gigx.GigxRRService",
	HandlerType: (*GigxRRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GigxRRService_SayHello_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GigxRRService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GigxRRService_Register_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _GigxRRService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GigxRRService_DeleteUser_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _GigxRRService_GetFile_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _GigxRRService_UpdateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _GigxRRService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllFiles",
			Handler:       _GigxRRService_GetAllFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gigxRR.proto",
}
