// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gigxRR.proto

package gigxRR

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//#Database modal structs
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ImagePath            string   `protobuf:"bytes,8,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	TotalSpace           int32    `protobuf:"varint,9,opt,name=total_space,json=totalSpace,proto3" json:"total_space,omitempty"`
	CreatedDate          string   `protobuf:"bytes,10,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,11,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	LanguageCode         string   `protobuf:"bytes,12,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	IsConfirmAccount     bool     `protobuf:"varint,13,opt,name=is_confirm_account,json=isConfirmAccount,proto3" json:"is_confirm_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *User) GetTotalSpace() int32 {
	if m != nil {
		return m.TotalSpace
	}
	return 0
}

func (m *User) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *User) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *User) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *User) GetIsConfirmAccount() bool {
	if m != nil {
		return m.IsConfirmAccount
	}
	return false
}

type Follow struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowerId           string   `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowedId           string   `protobuf:"bytes,3,opt,name=followed_id,json=followedId,proto3" json:"followed_id,omitempty"`
	FollowDate           string   `protobuf:"bytes,4,opt,name=follow_date,json=followDate,proto3" json:"follow_date,omitempty"`
	UnfollowDate         string   `protobuf:"bytes,5,opt,name=unfollow_date,json=unfollowDate,proto3" json:"unfollow_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Follow) Reset()         { *m = Follow{} }
func (m *Follow) String() string { return proto.CompactTextString(m) }
func (*Follow) ProtoMessage()    {}
func (*Follow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{1}
}

func (m *Follow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Follow.Unmarshal(m, b)
}
func (m *Follow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Follow.Marshal(b, m, deterministic)
}
func (m *Follow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Follow.Merge(m, src)
}
func (m *Follow) XXX_Size() int {
	return xxx_messageInfo_Follow.Size(m)
}
func (m *Follow) XXX_DiscardUnknown() {
	xxx_messageInfo_Follow.DiscardUnknown(m)
}

var xxx_messageInfo_Follow proto.InternalMessageInfo

func (m *Follow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Follow) GetFollowerId() string {
	if m != nil {
		return m.FollowerId
	}
	return ""
}

func (m *Follow) GetFollowedId() string {
	if m != nil {
		return m.FollowedId
	}
	return ""
}

func (m *Follow) GetFollowDate() string {
	if m != nil {
		return m.FollowDate
	}
	return ""
}

func (m *Follow) GetUnfollowDate() string {
	if m != nil {
		return m.UnfollowDate
	}
	return ""
}

type Folder struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedDate          string   `protobuf:"bytes,4,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Folder) Reset()         { *m = Folder{} }
func (m *Folder) String() string { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()    {}
func (*Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{2}
}

func (m *Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Folder.Unmarshal(m, b)
}
func (m *Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Folder.Marshal(b, m, deterministic)
}
func (m *Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Folder.Merge(m, src)
}
func (m *Folder) XXX_Size() int {
	return xxx_messageInfo_Folder.Size(m)
}
func (m *Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_Folder.DiscardUnknown(m)
}

var xxx_messageInfo_Folder proto.InternalMessageInfo

func (m *Folder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Folder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Folder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Folder) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Folder) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId             string   `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedDate          string   `protobuf:"bytes,6,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate          string   `protobuf:"bytes,7,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	FileHash             string   `protobuf:"bytes,8,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	IsBuried             bool     `protobuf:"varint,9,opt,name=is_buried,json=isBuried,proto3" json:"is_buried,omitempty"`
	IsFolderFile         bool     `protobuf:"varint,10,opt,name=is_folder_file,json=isFolderFile,proto3" json:"is_folder_file,omitempty"`
	IsStarred            bool     `protobuf:"varint,11,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	IsTrash              bool     `protobuf:"varint,12,opt,name=is_trash,json=isTrash,proto3" json:"is_trash,omitempty"`
	IsDeleted            bool     `protobuf:"varint,13,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *File) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *File) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *File) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

func (m *File) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *File) GetIsBuried() bool {
	if m != nil {
		return m.IsBuried
	}
	return false
}

func (m *File) GetIsFolderFile() bool {
	if m != nil {
		return m.IsFolderFile
	}
	return false
}

func (m *File) GetIsStarred() bool {
	if m != nil {
		return m.IsStarred
	}
	return false
}

func (m *File) GetIsTrash() bool {
	if m != nil {
		return m.IsTrash
	}
	return false
}

func (m *File) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Buried struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileHash             string   `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	PublicHash           string   `protobuf:"bytes,5,opt,name=public_hash,json=publicHash,proto3" json:"public_hash,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	BuriedDate           string   `protobuf:"bytes,7,opt,name=buried_date,json=buriedDate,proto3" json:"buried_date,omitempty"`
	DiggingDate          string   `protobuf:"bytes,8,opt,name=digging_date,json=diggingDate,proto3" json:"digging_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buried) Reset()         { *m = Buried{} }
func (m *Buried) String() string { return proto.CompactTextString(m) }
func (*Buried) ProtoMessage()    {}
func (*Buried) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{4}
}

func (m *Buried) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buried.Unmarshal(m, b)
}
func (m *Buried) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buried.Marshal(b, m, deterministic)
}
func (m *Buried) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buried.Merge(m, src)
}
func (m *Buried) XXX_Size() int {
	return xxx_messageInfo_Buried.Size(m)
}
func (m *Buried) XXX_DiscardUnknown() {
	xxx_messageInfo_Buried.DiscardUnknown(m)
}

var xxx_messageInfo_Buried proto.InternalMessageInfo

func (m *Buried) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Buried) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Buried) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Buried) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Buried) GetPublicHash() string {
	if m != nil {
		return m.PublicHash
	}
	return ""
}

func (m *Buried) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Buried) GetBuriedDate() string {
	if m != nil {
		return m.BuriedDate
	}
	return ""
}

func (m *Buried) GetDiggingDate() string {
	if m != nil {
		return m.DiggingDate
	}
	return ""
}

//Only for use login
type UserLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LanguageCode         string   `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	CountryFlag          string   `protobuf:"bytes,4,opt,name=country_flag,json=countryFlag,proto3" json:"country_flag,omitempty"`
	GmtOffSet            int32    `protobuf:"varint,5,opt,name=gmt_off_set,json=gmtOffSet,proto3" json:"gmt_off_set,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{5}
}

func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (m *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(m, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLogin) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *UserLogin) GetCountryFlag() string {
	if m != nil {
		return m.CountryFlag
	}
	return ""
}

func (m *UserLogin) GetGmtOffSet() int32 {
	if m != nil {
		return m.GmtOffSet
	}
	return 0
}

func (m *UserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GeneralRequest struct {
	EmailAddress                    string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	EmailType                       string   `protobuf:"bytes,2,opt,name=email_type,json=emailType,proto3" json:"email_type,omitempty"`
	RegisterVerificationToken       string   `protobuf:"bytes,3,opt,name=register_verification_token,json=registerVerificationToken,proto3" json:"register_verification_token,omitempty"`
	ForgotPasswordVerificationToken string   `protobuf:"bytes,4,opt,name=forgot_password_verification_token,json=forgotPasswordVerificationToken,proto3" json:"forgot_password_verification_token,omitempty"`
	Password                        string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm                 string   `protobuf:"bytes,6,opt,name=password_confirm,json=passwordConfirm,proto3" json:"password_confirm,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{6}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *GeneralRequest) GetEmailType() string {
	if m != nil {
		return m.EmailType
	}
	return ""
}

func (m *GeneralRequest) GetRegisterVerificationToken() string {
	if m != nil {
		return m.RegisterVerificationToken
	}
	return ""
}

func (m *GeneralRequest) GetForgotPasswordVerificationToken() string {
	if m != nil {
		return m.ForgotPasswordVerificationToken
	}
	return ""
}

func (m *GeneralRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GeneralRequest) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsEmailSuccess       bool     `protobuf:"varint,3,opt,name=is_email_success,json=isEmailSuccess,proto3" json:"is_email_success,omitempty"`
	IsTokenSuccess       bool     `protobuf:"varint,4,opt,name=is_token_success,json=isTokenSuccess,proto3" json:"is_token_success,omitempty"`
	IsOperationSuccess   bool     `protobuf:"varint,5,opt,name=is_operation_success,json=isOperationSuccess,proto3" json:"is_operation_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{7}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GeneralResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GeneralResponse) GetIsEmailSuccess() bool {
	if m != nil {
		return m.IsEmailSuccess
	}
	return false
}

func (m *GeneralResponse) GetIsTokenSuccess() bool {
	if m != nil {
		return m.IsTokenSuccess
	}
	return false
}

func (m *GeneralResponse) GetIsOperationSuccess() bool {
	if m != nil {
		return m.IsOperationSuccess
	}
	return false
}

type IpInformation struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	LanguageCode         string   `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	CountryFlag          string   `protobuf:"bytes,3,opt,name=country_flag,json=countryFlag,proto3" json:"country_flag,omitempty"`
	CountryCode          string   `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName          string   `protobuf:"bytes,5,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	GmtOffSet            int32    `protobuf:"varint,6,opt,name=gmt_off_set,json=gmtOffSet,proto3" json:"gmt_off_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpInformation) Reset()         { *m = IpInformation{} }
func (m *IpInformation) String() string { return proto.CompactTextString(m) }
func (*IpInformation) ProtoMessage()    {}
func (*IpInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{8}
}

func (m *IpInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpInformation.Unmarshal(m, b)
}
func (m *IpInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpInformation.Marshal(b, m, deterministic)
}
func (m *IpInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpInformation.Merge(m, src)
}
func (m *IpInformation) XXX_Size() int {
	return xxx_messageInfo_IpInformation.Size(m)
}
func (m *IpInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_IpInformation.DiscardUnknown(m)
}

var xxx_messageInfo_IpInformation proto.InternalMessageInfo

func (m *IpInformation) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *IpInformation) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *IpInformation) GetCountryFlag() string {
	if m != nil {
		return m.CountryFlag
	}
	return ""
}

func (m *IpInformation) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *IpInformation) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *IpInformation) GetGmtOffSet() int32 {
	if m != nil {
		return m.GmtOffSet
	}
	return 0
}

//Check is service working ?
type HelloRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{9}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{10}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//User methods start
type RegisterUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{11}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{12}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

type CheckUserToRegisterRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserToRegisterRequest) Reset()         { *m = CheckUserToRegisterRequest{} }
func (m *CheckUserToRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserToRegisterRequest) ProtoMessage()    {}
func (*CheckUserToRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{13}
}

func (m *CheckUserToRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserToRegisterRequest.Unmarshal(m, b)
}
func (m *CheckUserToRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserToRegisterRequest.Marshal(b, m, deterministic)
}
func (m *CheckUserToRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserToRegisterRequest.Merge(m, src)
}
func (m *CheckUserToRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserToRegisterRequest.Size(m)
}
func (m *CheckUserToRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserToRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserToRegisterRequest proto.InternalMessageInfo

func (m *CheckUserToRegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CheckUserToRegisterResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CheckUserToRegisterResponse) Reset()         { *m = CheckUserToRegisterResponse{} }
func (m *CheckUserToRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUserToRegisterResponse) ProtoMessage()    {}
func (*CheckUserToRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{14}
}

func (m *CheckUserToRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserToRegisterResponse.Unmarshal(m, b)
}
func (m *CheckUserToRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserToRegisterResponse.Marshal(b, m, deterministic)
}
func (m *CheckUserToRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserToRegisterResponse.Merge(m, src)
}
func (m *CheckUserToRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUserToRegisterResponse.Size(m)
}
func (m *CheckUserToRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserToRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserToRegisterResponse proto.InternalMessageInfo

func (m *CheckUserToRegisterResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

type LoginUserRequest struct {
	User                 *UserLogin `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{15}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUser() *UserLogin {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserResponse struct {
	User                 *UserLogin `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{16}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *UserLogin {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{17}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{18}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{19}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{20}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

//User methods finish
type UpdateFileRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{21}
}

func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(m, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type UpdateFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileResponse) Reset()         { *m = UpdateFileResponse{} }
func (m *UpdateFileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFileResponse) ProtoMessage()    {}
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{22}
}

func (m *UpdateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileResponse.Unmarshal(m, b)
}
func (m *UpdateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileResponse.Merge(m, src)
}
func (m *UpdateFileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFileResponse.Size(m)
}
func (m *UpdateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileResponse proto.InternalMessageInfo

func (m *UpdateFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{23}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *GetFileRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type GetFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{24}
}

func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (m *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(m, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetAllFilesRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFilesRequest) Reset()         { *m = GetAllFilesRequest{} }
func (m *GetAllFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllFilesRequest) ProtoMessage()    {}
func (*GetAllFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{25}
}

func (m *GetAllFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFilesRequest.Unmarshal(m, b)
}
func (m *GetAllFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFilesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFilesRequest.Merge(m, src)
}
func (m *GetAllFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllFilesRequest.Size(m)
}
func (m *GetAllFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFilesRequest proto.InternalMessageInfo

func (m *GetAllFilesRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type GetAllFilesResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFilesResponse) Reset()         { *m = GetAllFilesResponse{} }
func (m *GetAllFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllFilesResponse) ProtoMessage()    {}
func (*GetAllFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{26}
}

func (m *GetAllFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFilesResponse.Unmarshal(m, b)
}
func (m *GetAllFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFilesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFilesResponse.Merge(m, src)
}
func (m *GetAllFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllFilesResponse.Size(m)
}
func (m *GetAllFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFilesResponse proto.InternalMessageInfo

func (m *GetAllFilesResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type DeleteFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{27}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *DeleteFileRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type DeleteFileResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{28}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

type SendEmailRequest struct {
	GeneralRequest       *GeneralRequest `protobuf:"bytes,1,opt,name=generalRequest,proto3" json:"generalRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{29}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetGeneralRequest() *GeneralRequest {
	if m != nil {
		return m.GeneralRequest
	}
	return nil
}

type SendEmailResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{30}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

type CheckVerificationLinkRequest struct {
	GeneralRequest       *GeneralRequest `protobuf:"bytes,1,opt,name=generalRequest,proto3" json:"generalRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CheckVerificationLinkRequest) Reset()         { *m = CheckVerificationLinkRequest{} }
func (m *CheckVerificationLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationLinkRequest) ProtoMessage()    {}
func (*CheckVerificationLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{31}
}

func (m *CheckVerificationLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationLinkRequest.Unmarshal(m, b)
}
func (m *CheckVerificationLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationLinkRequest.Marshal(b, m, deterministic)
}
func (m *CheckVerificationLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationLinkRequest.Merge(m, src)
}
func (m *CheckVerificationLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationLinkRequest.Size(m)
}
func (m *CheckVerificationLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationLinkRequest proto.InternalMessageInfo

func (m *CheckVerificationLinkRequest) GetGeneralRequest() *GeneralRequest {
	if m != nil {
		return m.GeneralRequest
	}
	return nil
}

type CheckVerificationLinkResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CheckVerificationLinkResponse) Reset()         { *m = CheckVerificationLinkResponse{} }
func (m *CheckVerificationLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationLinkResponse) ProtoMessage()    {}
func (*CheckVerificationLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{32}
}

func (m *CheckVerificationLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationLinkResponse.Unmarshal(m, b)
}
func (m *CheckVerificationLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationLinkResponse.Marshal(b, m, deterministic)
}
func (m *CheckVerificationLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationLinkResponse.Merge(m, src)
}
func (m *CheckVerificationLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationLinkResponse.Size(m)
}
func (m *CheckVerificationLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationLinkResponse proto.InternalMessageInfo

func (m *CheckVerificationLinkResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

type GetIpInformationRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIpInformationRequest) Reset()         { *m = GetIpInformationRequest{} }
func (m *GetIpInformationRequest) String() string { return proto.CompactTextString(m) }
func (*GetIpInformationRequest) ProtoMessage()    {}
func (*GetIpInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{33}
}

func (m *GetIpInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIpInformationRequest.Unmarshal(m, b)
}
func (m *GetIpInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIpInformationRequest.Marshal(b, m, deterministic)
}
func (m *GetIpInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIpInformationRequest.Merge(m, src)
}
func (m *GetIpInformationRequest) XXX_Size() int {
	return xxx_messageInfo_GetIpInformationRequest.Size(m)
}
func (m *GetIpInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIpInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIpInformationRequest proto.InternalMessageInfo

func (m *GetIpInformationRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetIpInformationResponse struct {
	IpInformation        *IpInformation `protobuf:"bytes,1,opt,name=ip_information,json=ipInformation,proto3" json:"ip_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetIpInformationResponse) Reset()         { *m = GetIpInformationResponse{} }
func (m *GetIpInformationResponse) String() string { return proto.CompactTextString(m) }
func (*GetIpInformationResponse) ProtoMessage()    {}
func (*GetIpInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{34}
}

func (m *GetIpInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIpInformationResponse.Unmarshal(m, b)
}
func (m *GetIpInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIpInformationResponse.Marshal(b, m, deterministic)
}
func (m *GetIpInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIpInformationResponse.Merge(m, src)
}
func (m *GetIpInformationResponse) XXX_Size() int {
	return xxx_messageInfo_GetIpInformationResponse.Size(m)
}
func (m *GetIpInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIpInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIpInformationResponse proto.InternalMessageInfo

func (m *GetIpInformationResponse) GetIpInformation() *IpInformation {
	if m != nil {
		return m.IpInformation
	}
	return nil
}

type ResetUserPasswordRequest struct {
	GeneralRequest       *GeneralRequest `protobuf:"bytes,1,opt,name=generalRequest,proto3" json:"generalRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResetUserPasswordRequest) Reset()         { *m = ResetUserPasswordRequest{} }
func (m *ResetUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordRequest) ProtoMessage()    {}
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{35}
}

func (m *ResetUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordRequest.Unmarshal(m, b)
}
func (m *ResetUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordRequest.Merge(m, src)
}
func (m *ResetUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordRequest.Size(m)
}
func (m *ResetUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordRequest proto.InternalMessageInfo

func (m *ResetUserPasswordRequest) GetGeneralRequest() *GeneralRequest {
	if m != nil {
		return m.GeneralRequest
	}
	return nil
}

type ResetUserPasswordResponse struct {
	GeneralResponse      *GeneralResponse `protobuf:"bytes,1,opt,name=general_response,json=generalResponse,proto3" json:"general_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResetUserPasswordResponse) Reset()         { *m = ResetUserPasswordResponse{} }
func (m *ResetUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetUserPasswordResponse) ProtoMessage()    {}
func (*ResetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce114fac961b177, []int{36}
}

func (m *ResetUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUserPasswordResponse.Unmarshal(m, b)
}
func (m *ResetUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUserPasswordResponse.Merge(m, src)
}
func (m *ResetUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetUserPasswordResponse.Size(m)
}
func (m *ResetUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUserPasswordResponse proto.InternalMessageInfo

func (m *ResetUserPasswordResponse) GetGeneralResponse() *GeneralResponse {
	if m != nil {
		return m.GeneralResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "gigx.User")
	proto.RegisterType((*Follow)(nil), "gigx.Follow")
	proto.RegisterType((*Folder)(nil), "gigx.Folder")
	proto.RegisterType((*File)(nil), "gigx.File")
	proto.RegisterType((*Buried)(nil), "gigx.Buried")
	proto.RegisterType((*UserLogin)(nil), "gigx.UserLogin")
	proto.RegisterType((*GeneralRequest)(nil), "gigx.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "gigx.GeneralResponse")
	proto.RegisterType((*IpInformation)(nil), "gigx.IpInformation")
	proto.RegisterType((*HelloRequest)(nil), "gigx.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "gigx.HelloResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "gigx.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "gigx.RegisterUserResponse")
	proto.RegisterType((*CheckUserToRegisterRequest)(nil), "gigx.CheckUserToRegisterRequest")
	proto.RegisterType((*CheckUserToRegisterResponse)(nil), "gigx.CheckUserToRegisterResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "gigx.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "gigx.LoginUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "gigx.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "gigx.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "gigx.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "gigx.DeleteUserResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "gigx.UpdateFileRequest")
	proto.RegisterType((*UpdateFileResponse)(nil), "gigx.UpdateFileResponse")
	proto.RegisterType((*GetFileRequest)(nil), "gigx.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "gigx.GetFileResponse")
	proto.RegisterType((*GetAllFilesRequest)(nil), "gigx.GetAllFilesRequest")
	proto.RegisterType((*GetAllFilesResponse)(nil), "gigx.GetAllFilesResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "gigx.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "gigx.DeleteFileResponse")
	proto.RegisterType((*SendEmailRequest)(nil), "gigx.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "gigx.SendEmailResponse")
	proto.RegisterType((*CheckVerificationLinkRequest)(nil), "gigx.CheckVerificationLinkRequest")
	proto.RegisterType((*CheckVerificationLinkResponse)(nil), "gigx.CheckVerificationLinkResponse")
	proto.RegisterType((*GetIpInformationRequest)(nil), "gigx.GetIpInformationRequest")
	proto.RegisterType((*GetIpInformationResponse)(nil), "gigx.GetIpInformationResponse")
	proto.RegisterType((*ResetUserPasswordRequest)(nil), "gigx.ResetUserPasswordRequest")
	proto.RegisterType((*ResetUserPasswordResponse)(nil), "gigx.ResetUserPasswordResponse")
}

func init() { proto.RegisterFile("proto/gigxRR.proto", fileDescriptor_9ce114fac961b177) }

var fileDescriptor_9ce114fac961b177 = []byte{
	// 1529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x86, 0xfe, 0xa9, 0x23, 0xd9, 0x96, 0xc7, 0xce, 0x35, 0xad, 0xdc, 0xd8, 0x0e, 0x73, 0x17,
	0x0e, 0x10, 0xe4, 0xe6, 0xe6, 0xe7, 0x36, 0x28, 0x82, 0xb6, 0x4e, 0x52, 0x3b, 0x46, 0x83, 0x26,
	0xa5, 0x9c, 0x20, 0x08, 0x5a, 0xb0, 0x8c, 0x38, 0xa2, 0x07, 0xa1, 0x44, 0x96, 0x33, 0x4a, 0xea,
	0x65, 0xd7, 0x45, 0xdf, 0xa1, 0xcb, 0xbe, 0x46, 0x57, 0x7d, 0x89, 0x3e, 0x40, 0xd7, 0x7d, 0x82,
	0x62, 0xfe, 0xc4, 0x21, 0x29, 0xff, 0x04, 0xd1, 0x4e, 0xf3, 0x9d, 0xef, 0x9c, 0x39, 0x7f, 0x73,
	0x0e, 0x21, 0x40, 0x49, 0x1a, 0xb3, 0xf8, 0xbf, 0x21, 0x09, 0x7f, 0x74, 0xdd, 0x9b, 0xe2, 0x80,
	0xea, 0xfc, 0xe4, 0xfc, 0x52, 0x83, 0xfa, 0x0b, 0x8a, 0x53, 0xb4, 0x0c, 0x55, 0x12, 0xd8, 0x95,
	0x9d, 0xca, 0x6e, 0xdb, 0xad, 0x92, 0x00, 0x21, 0xa8, 0x4f, 0xfc, 0x31, 0xb6, 0xab, 0x02, 0x11,
	0xbf, 0x91, 0x0d, 0x2d, 0x3a, 0x4d, 0x05, 0x5c, 0x13, 0xb0, 0x3e, 0xa2, 0x75, 0x68, 0xe0, 0xb1,
	0x4f, 0x22, 0xbb, 0x2e, 0x70, 0x79, 0x40, 0x7d, 0xb0, 0xa6, 0x14, 0x4b, 0x85, 0x86, 0x10, 0xcc,
	0xce, 0x5c, 0x96, 0xf8, 0x94, 0xbe, 0x8f, 0xd3, 0xc0, 0x6e, 0x4a, 0x99, 0x3e, 0xa3, 0x1d, 0xe8,
	0x04, 0x98, 0x0e, 0x53, 0x92, 0x30, 0x12, 0x4f, 0xec, 0x96, 0x10, 0x9b, 0x10, 0xba, 0x02, 0x40,
	0xc6, 0x7e, 0x88, 0xbd, 0xc4, 0x67, 0xc7, 0xb6, 0x25, 0x08, 0x6d, 0x81, 0x3c, 0xf7, 0xd9, 0x31,
	0xda, 0x86, 0x0e, 0x8b, 0x99, 0x1f, 0x79, 0x34, 0xf1, 0x87, 0xd8, 0x6e, 0xef, 0x54, 0x76, 0x1b,
	0x2e, 0x08, 0x68, 0xc0, 0x11, 0x74, 0x15, 0xba, 0xc3, 0x14, 0xfb, 0x0c, 0x07, 0x5e, 0xe0, 0x33,
	0x6c, 0x83, 0xbc, 0x42, 0x61, 0x8f, 0x7d, 0x26, 0x28, 0xd3, 0x24, 0xc8, 0x28, 0x1d, 0x49, 0x51,
	0x98, 0xa0, 0x5c, 0x83, 0xa5, 0xc8, 0x9f, 0x84, 0x53, 0xee, 0xc8, 0x30, 0x0e, 0xb0, 0xdd, 0x15,
	0x9c, 0xae, 0x06, 0x1f, 0xc5, 0x01, 0x46, 0x37, 0x00, 0x11, 0xea, 0x0d, 0xe3, 0xc9, 0x88, 0xa4,
	0x63, 0xcf, 0x1f, 0x0e, 0xe3, 0xe9, 0x84, 0xd9, 0x4b, 0x3b, 0x95, 0x5d, 0xcb, 0xed, 0x11, 0xfa,
	0x48, 0x0a, 0xf6, 0x24, 0xee, 0xfc, 0x5a, 0x81, 0xe6, 0x7e, 0x1c, 0x45, 0xf1, 0xfb, 0x52, 0x45,
	0xb6, 0xa1, 0x33, 0x12, 0x12, 0x9c, 0x7a, 0x24, 0x50, 0x85, 0x01, 0x0d, 0x1d, 0x9a, 0x84, 0x80,
	0x13, 0x6a, 0x39, 0x42, 0x60, 0x12, 0x64, 0x44, 0x75, 0x93, 0xa0, 0x03, 0x9a, 0x4e, 0x4c, 0x8a,
	0xac, 0x5a, 0x57, 0x83, 0x9c, 0xe4, 0xfc, 0x2c, 0x5d, 0x0c, 0x2e, 0xd8, 0x34, 0x1b, 0xd0, 0xe2,
	0x45, 0xcf, 0x3c, 0x6a, 0xf2, 0xe3, 0x61, 0x50, 0xaa, 0x41, 0xfd, 0xfc, 0x1a, 0x34, 0x4a, 0x35,
	0x70, 0x7e, 0xaa, 0x41, 0x7d, 0x9f, 0x44, 0xb8, 0xe4, 0x8b, 0x71, 0x6f, 0x35, 0x77, 0xef, 0x65,
	0x68, 0x8f, 0x84, 0xfb, 0x99, 0x4b, 0x96, 0x04, 0x0e, 0xb3, 0x08, 0xea, 0x46, 0x04, 0x85, 0x76,
	0x6c, 0x94, 0xdb, 0xb1, 0x18, 0x4a, 0xf3, 0xfc, 0x50, 0x5a, 0xe5, 0x76, 0xe2, 0x8e, 0x91, 0x08,
	0x7b, 0xc7, 0x3e, 0xd5, 0x3d, 0x6d, 0x71, 0xe0, 0x89, 0x4f, 0x8f, 0xb9, 0x90, 0x50, 0xef, 0xcd,
	0x34, 0x25, 0x38, 0x10, 0x0d, 0x6d, 0xb9, 0x16, 0xa1, 0x0f, 0xc5, 0x19, 0xfd, 0x07, 0x96, 0x09,
	0xf5, 0x54, 0x54, 0x5c, 0x45, 0x34, 0xb4, 0xe5, 0x76, 0x09, 0x95, 0x95, 0x12, 0x19, 0xe2, 0x8f,
	0x86, 0x7a, 0x94, 0xf9, 0x69, 0x8a, 0x03, 0xd1, 0xcf, 0x96, 0xdb, 0x26, 0x74, 0x20, 0x01, 0xb4,
	0x09, 0x16, 0xa1, 0x1e, 0x4b, 0xf9, 0xed, 0x5d, 0x21, 0x6c, 0x11, 0x7a, 0xc4, 0x8f, 0x4a, 0x33,
	0xc0, 0x11, 0x66, 0x38, 0x50, 0xbd, 0xdb, 0x26, 0xf4, 0xb1, 0x04, 0x9c, 0xbf, 0x2b, 0xd0, 0x54,
	0x9e, 0x7c, 0x50, 0x15, 0x78, 0xb0, 0xc6, 0x34, 0x11, 0xc1, 0x7e, 0xcd, 0x33, 0x9e, 0xcb, 0x44,
	0xbd, 0x90, 0x89, 0x6d, 0xe8, 0x24, 0xd3, 0x37, 0x11, 0x19, 0x4a, 0xb1, 0x2c, 0x07, 0x48, 0x48,
	0x10, 0x0a, 0xf5, 0x6a, 0x96, 0xeb, 0xb5, 0x0d, 0x1d, 0x99, 0x49, 0xb3, 0x16, 0x20, 0x21, 0x5d,
	0xad, 0x80, 0x84, 0x21, 0x99, 0x84, 0x92, 0x61, 0x29, 0x1b, 0x12, 0x13, 0x8d, 0xf7, 0x7b, 0x05,
	0xda, 0x7c, 0x72, 0x3e, 0x8d, 0x43, 0x32, 0xc9, 0x8d, 0xba, 0xca, 0x19, 0xa3, 0xae, 0x5a, 0x18,
	0x75, 0xa5, 0x11, 0x52, 0x9b, 0x33, 0x42, 0x78, 0x7b, 0xf1, 0xe9, 0x90, 0x9e, 0x78, 0xa3, 0xc8,
	0x0f, 0x67, 0x2f, 0x45, 0x62, 0xfb, 0x91, 0x1f, 0xa2, 0x2d, 0xe8, 0x84, 0x63, 0xe6, 0xc5, 0xa3,
	0x91, 0x47, 0x31, 0x13, 0x49, 0x69, 0xb8, 0xed, 0x70, 0xcc, 0x9e, 0x8d, 0x46, 0x03, 0xcc, 0xf8,
	0x80, 0x66, 0xf1, 0x5b, 0xac, 0xb3, 0x21, 0x0f, 0xce, 0x6f, 0x55, 0x58, 0x3e, 0xc0, 0x13, 0x9c,
	0xfa, 0x91, 0x8b, 0x7f, 0x98, 0x62, 0xca, 0xb8, 0x43, 0x62, 0x78, 0x7b, 0x7e, 0x10, 0xa4, 0x98,
	0x52, 0x15, 0x4d, 0x57, 0x80, 0x7b, 0x12, 0xe3, 0xfd, 0x20, 0x49, 0xec, 0x24, 0xd1, 0xaf, 0xbd,
	0x2d, 0x90, 0xa3, 0x93, 0x04, 0xa3, 0xcf, 0xe0, 0x72, 0x8a, 0x43, 0x42, 0x19, 0x4e, 0xbd, 0x77,
	0x38, 0x25, 0x23, 0x32, 0xf4, 0x79, 0xde, 0x3d, 0xe9, 0x82, 0x0c, 0x71, 0x53, 0x53, 0x5e, 0x1a,
	0x8c, 0x23, 0x4e, 0x40, 0x5f, 0x81, 0x33, 0x8a, 0xd3, 0x30, 0x66, 0x9e, 0xce, 0xd3, 0x3c, 0x33,
	0x32, 0x0b, 0xdb, 0x92, 0xf9, 0x5c, 0x11, 0xcb, 0xc6, 0xcc, 0xec, 0x37, 0x0a, 0xd9, 0xbf, 0x0e,
	0xbd, 0xd9, 0x0d, 0x6a, 0x42, 0xab, 0x04, 0xad, 0x68, 0x5c, 0xcd, 0x67, 0xe7, 0x8f, 0x0a, 0xac,
	0xcc, 0x52, 0x45, 0x93, 0x78, 0x42, 0xc5, 0x3e, 0x1c, 0x63, 0x4a, 0xfd, 0x50, 0xd7, 0x5c, 0x1f,
	0xb3, 0x74, 0x57, 0x8d, 0x74, 0xa3, 0x5d, 0xe8, 0x11, 0xea, 0xc9, 0xcc, 0xd1, 0xe9, 0x70, 0xc8,
	0xd3, 0x5b, 0x13, 0x8f, 0x69, 0x99, 0xd0, 0x2f, 0x39, 0x3c, 0x90, 0xa8, 0x62, 0x0a, 0xad, 0x19,
	0xb3, 0xae, 0x99, 0x22, 0x2e, 0xcd, 0xbc, 0x05, 0xeb, 0x84, 0x7a, 0x71, 0x82, 0x53, 0x99, 0x1b,
	0xcd, 0x6e, 0x08, 0x36, 0x22, 0xf4, 0x99, 0x16, 0x29, 0x0d, 0xe7, 0xcf, 0x0a, 0x2c, 0x1d, 0x26,
	0x87, 0x93, 0x51, 0x9c, 0x8e, 0xfd, 0xd9, 0x36, 0x4d, 0x0a, 0x05, 0x6f, 0x93, 0x44, 0x57, 0xbb,
	0xd4, 0xa3, 0xd5, 0x0b, 0xf4, 0x68, 0xad, 0xdc, 0xa3, 0x06, 0x45, 0x98, 0xc9, 0xb7, 0x71, 0xd1,
	0x8a, 0xf1, 0xd5, 0xa0, 0x29, 0x62, 0x36, 0x14, 0x3a, 0xbd, 0x59, 0xe8, 0x74, 0x67, 0x17, 0xba,
	0x4f, 0x70, 0x14, 0xc5, 0xba, 0xa1, 0x4f, 0x2d, 0x92, 0x73, 0x1d, 0x96, 0x14, 0xf3, 0xbc, 0x7a,
	0x3a, 0xf7, 0x60, 0xcd, 0x55, 0xed, 0xca, 0xdf, 0xbc, 0xb6, 0xbd, 0x05, 0x75, 0xfe, 0xca, 0x05,
	0xbb, 0x73, 0x1b, 0x6e, 0xf2, 0x4f, 0xaa, 0x9b, 0x82, 0x20, 0x70, 0xe7, 0x15, 0xac, 0xe7, 0xd5,
	0xd4, 0x45, 0x5f, 0x40, 0x2f, 0x94, 0xbd, 0xe4, 0xa5, 0x0a, 0x53, 0x36, 0x2e, 0x49, 0x1b, 0x85,
	0x4e, 0x73, 0x57, 0xc2, 0x3c, 0xe0, 0x3c, 0x80, 0xfe, 0xa3, 0x63, 0x3c, 0x7c, 0xcb, 0xcd, 0x1e,
	0xc5, 0xfa, 0x92, 0x8b, 0xfa, 0xe5, 0xc1, 0xe5, 0xb9, 0xda, 0x0b, 0x73, 0xef, 0x13, 0xe8, 0x89,
	0xb9, 0x68, 0x26, 0xeb, 0x5a, 0xce, 0xa9, 0x95, 0xcc, 0x29, 0xc1, 0x54, 0x9e, 0xdd, 0x87, 0x55,
	0x43, 0x51, 0xf9, 0x73, 0x21, 0xcd, 0x3b, 0xb0, 0xfa, 0x42, 0x2c, 0xd3, 0x0f, 0x29, 0xd0, 0x5d,
	0x40, 0xa6, 0x92, 0xba, 0xef, 0x3c, 0xad, 0x1b, 0xb0, 0x2a, 0x57, 0x9f, 0x79, 0x95, 0xb1, 0xe9,
	0x2a, 0xe6, 0xa6, 0x73, 0x5e, 0x02, 0x32, 0xd9, 0x0b, 0xcb, 0xf1, 0x2c, 0x60, 0xbe, 0xdc, 0x8d,
	0x80, 0xc5, 0xfe, 0xcf, 0xb9, 0x2e, 0x08, 0x02, 0xcf, 0x02, 0x96, 0x4a, 0x59, 0xc0, 0x67, 0x6a,
	0xed, 0xf3, 0x35, 0xc1, 0xcc, 0x7b, 0x36, 0xa0, 0x25, 0x36, 0x74, 0x16, 0x2d, 0x3f, 0x1a, 0x7b,
	0x5d, 0xec, 0xe6, 0x6a, 0x7e, 0x75, 0x3b, 0xff, 0xe3, 0x33, 0x94, 0x7d, 0xd0, 0xd5, 0x77, 0x01,
	0x1d, 0x60, 0xb6, 0x17, 0x45, 0x1c, 0xa3, 0x17, 0x0d, 0xf3, 0x1e, 0xac, 0xe5, 0xb4, 0x2e, 0x78,
	0xd9, 0xa1, 0x2e, 0xec, 0xc7, 0x87, 0x3a, 0xab, 0x7a, 0x2e, 0xda, 0x8f, 0xaf, 0xfa, 0x73, 0xe8,
	0x0d, 0xf0, 0x24, 0x10, 0xdb, 0x42, 0x7b, 0xf8, 0x00, 0x96, 0xc3, 0xdc, 0x16, 0x57, 0x36, 0xd7,
	0x0b, 0x36, 0x85, 0xcc, 0x2d, 0x70, 0x9d, 0x17, 0xb0, 0x6a, 0x58, 0x5c, 0x98, 0xa3, 0xdf, 0xc2,
	0xbf, 0xc5, 0x8c, 0x31, 0x37, 0xf2, 0x53, 0x32, 0x79, 0xbb, 0x18, 0xa7, 0x7d, 0xb8, 0x72, 0x8a,
	0xf5, 0x05, 0xbe, 0xaf, 0x8d, 0x03, 0xcc, 0x72, 0x9b, 0xf2, 0xfc, 0x9d, 0xf2, 0x12, 0xec, 0xb2,
	0x92, 0x72, 0xe9, 0x53, 0x58, 0x26, 0x89, 0x47, 0x32, 0x89, 0x72, 0x68, 0x4d, 0x3a, 0x94, 0x57,
	0x5a, 0x22, 0xe6, 0xd1, 0x79, 0x05, 0xb6, 0x8b, 0x29, 0x66, 0x7c, 0x86, 0xe8, 0x6f, 0x9d, 0xc5,
	0x64, 0xf2, 0x3b, 0xd8, 0x9c, 0x63, 0x79, 0x51, 0x59, 0xbc, 0xfd, 0x57, 0x0b, 0x96, 0x0e, 0xc4,
	0xff, 0x0e, 0x03, 0x9c, 0xbe, 0x23, 0x43, 0x8c, 0xee, 0x80, 0x35, 0xf0, 0x4f, 0xc4, 0xe6, 0x45,
	0x48, 0x5a, 0x31, 0x17, 0x76, 0x7f, 0x2d, 0x87, 0x29, 0x47, 0xee, 0x43, 0x43, 0x7e, 0x68, 0xff,
	0x4b, 0x4a, 0x8b, 0xdb, 0xa5, 0xbf, 0x51, 0xc2, 0x95, 0xe6, 0x1e, 0x58, 0x7a, 0xc1, 0xa1, 0x4d,
	0x49, 0x9a, 0xb3, 0xca, 0xfb, 0xfd, 0x79, 0x22, 0x65, 0xe2, 0x35, 0xac, 0xcd, 0x59, 0x97, 0x68,
	0x47, 0xaa, 0x9c, 0xbe, 0x87, 0xfb, 0x57, 0xcf, 0x60, 0x28, 0xdb, 0x47, 0xb0, 0x5a, 0x4a, 0x3f,
	0xda, 0xd2, 0xce, 0xcc, 0xaf, 0x78, 0x7f, 0xfb, 0x54, 0xb9, 0xb2, 0xfa, 0x39, 0x40, 0xb6, 0xd7,
	0x90, 0xca, 0x4d, 0x69, 0x3d, 0xf6, 0xed, 0xb2, 0x20, 0x33, 0x90, 0x2d, 0x2d, 0x6d, 0xa0, 0xb4,
	0xf4, 0xb4, 0x81, 0x39, 0xfb, 0xed, 0x01, 0xb4, 0x67, 0x53, 0x45, 0x17, 0xad, 0x38, 0xb8, 0x74,
	0xd1, 0xca, 0xe3, 0xe7, 0x1b, 0xe8, 0x15, 0x9f, 0x11, 0xba, 0xa2, 0x3b, 0x6e, 0xee, 0x9b, 0xec,
	0x6f, 0x9d, 0x26, 0x56, 0x26, 0xbf, 0x87, 0x4b, 0x73, 0x27, 0x06, 0x72, 0x8c, 0x22, 0x9d, 0x32,
	0xac, 0xfa, 0xd7, 0xce, 0xe4, 0xa8, 0x1b, 0xfe, 0x0f, 0x2d, 0xb5, 0xdd, 0xd0, 0xec, 0xe9, 0x99,
	0x4b, 0xb3, 0x7f, 0xa9, 0x80, 0x2a, 0xbd, 0xc7, 0xd0, 0x31, 0x96, 0x15, 0xb2, 0x67, 0xac, 0xc2,
	0xd6, 0xeb, 0x6f, 0xce, 0x91, 0x48, 0x1b, 0xb7, 0x2a, 0x59, 0xc9, 0x85, 0x03, 0xb9, 0x92, 0x9b,
	0x3e, 0xd8, 0x65, 0x41, 0xb1, 0xe4, 0xa6, 0x81, 0xd2, 0x3a, 0xcc, 0x97, 0xdc, 0x34, 0xf0, 0xd0,
	0x7a, 0xdd, 0x94, 0xff, 0x30, 0xbe, 0x69, 0x8a, 0xbf, 0x18, 0xef, 0xfc, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0xf8, 0x1f, 0xef, 0x78, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GigxRRServiceClient is the client API for GigxRRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GigxRRServiceClient interface {
	//Say Hello
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	//User methods
	Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	CheckUserToRegister(ctx context.Context, in *CheckUserToRegisterRequest, opts ...grpc.CallOption) (*CheckUserToRegisterResponse, error)
	ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	//Services
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	GetIpInformation(ctx context.Context, in *GetIpInformationRequest, opts ...grpc.CallOption) (*GetIpInformationResponse, error)
	CheckVerificationLink(ctx context.Context, in *CheckVerificationLinkRequest, opts ...grpc.CallOption) (*CheckVerificationLinkResponse, error)
	//File methods
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetAllFiles(ctx context.Context, in *GetAllFilesRequest, opts ...grpc.CallOption) (GigxRRService_GetAllFilesClient, error)
	UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type gigxRRServiceClient struct {
	cc *grpc.ClientConn
}

func NewGigxRRServiceClient(cc *grpc.ClientConn) GigxRRServiceClient {
	return &gigxRRServiceClient{cc}
}

func (c *gigxRRServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) CheckUserToRegister(ctx context.Context, in *CheckUserToRegisterRequest, opts ...grpc.CallOption) (*CheckUserToRegisterResponse, error) {
	out := new(CheckUserToRegisterResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/CheckUserToRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*ResetUserPasswordResponse, error) {
	out := new(ResetUserPasswordResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/ResetUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) GetIpInformation(ctx context.Context, in *GetIpInformationRequest, opts ...grpc.CallOption) (*GetIpInformationResponse, error) {
	out := new(GetIpInformationResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/GetIpInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) CheckVerificationLink(ctx context.Context, in *CheckVerificationLinkRequest, opts ...grpc.CallOption) (*CheckVerificationLinkResponse, error) {
	out := new(CheckVerificationLinkResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/CheckVerificationLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) GetAllFiles(ctx context.Context, in *GetAllFilesRequest, opts ...grpc.CallOption) (GigxRRService_GetAllFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GigxRRService_serviceDesc.Streams[0], "/gigx.GigxRRService/GetAllFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &gigxRRServiceGetAllFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GigxRRService_GetAllFilesClient interface {
	Recv() (*GetAllFilesResponse, error)
	grpc.ClientStream
}

type gigxRRServiceGetAllFilesClient struct {
	grpc.ClientStream
}

func (x *gigxRRServiceGetAllFilesClient) Recv() (*GetAllFilesResponse, error) {
	m := new(GetAllFilesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gigxRRServiceClient) UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error) {
	out := new(UpdateFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/UpdateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gigxRRServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/gigx.GigxRRService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GigxRRServiceServer is the server API for GigxRRService service.
type GigxRRServiceServer interface {
	//Say Hello
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	//User methods
	Login(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	CheckUserToRegister(context.Context, *CheckUserToRegisterRequest) (*CheckUserToRegisterResponse, error)
	ResetUserPassword(context.Context, *ResetUserPasswordRequest) (*ResetUserPasswordResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	//Services
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	GetIpInformation(context.Context, *GetIpInformationRequest) (*GetIpInformationResponse, error)
	CheckVerificationLink(context.Context, *CheckVerificationLinkRequest) (*CheckVerificationLinkResponse, error)
	//File methods
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetAllFiles(*GetAllFilesRequest, GigxRRService_GetAllFilesServer) error
	UpdateFile(context.Context, *UpdateFileRequest) (*UpdateFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
}

func RegisterGigxRRServiceServer(s *grpc.Server, srv GigxRRServiceServer) {
	s.RegisterService(&_GigxRRService_serviceDesc, srv)
}

func _GigxRRService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).Login(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_CheckUserToRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserToRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).CheckUserToRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/CheckUserToRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).CheckUserToRegister(ctx, req.(*CheckUserToRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_ResetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).ResetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/ResetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).ResetUserPassword(ctx, req.(*ResetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_GetIpInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIpInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).GetIpInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/GetIpInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).GetIpInformation(ctx, req.(*GetIpInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_CheckVerificationLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVerificationLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).CheckVerificationLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/CheckVerificationLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).CheckVerificationLink(ctx, req.(*CheckVerificationLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_GetAllFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GigxRRServiceServer).GetAllFiles(m, &gigxRRServiceGetAllFilesServer{stream})
}

type GigxRRService_GetAllFilesServer interface {
	Send(*GetAllFilesResponse) error
	grpc.ServerStream
}

type gigxRRServiceGetAllFilesServer struct {
	grpc.ServerStream
}

func (x *gigxRRServiceGetAllFilesServer) Send(m *GetAllFilesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GigxRRService_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/UpdateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).UpdateFile(ctx, req.(*UpdateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GigxRRService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigxRRServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigx.GigxRRService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigxRRServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GigxRRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gigx.GigxRRService",
	HandlerType: (*GigxRRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GigxRRService_SayHello_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GigxRRService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GigxRRService_Register_Handler,
		},
		{
			MethodName: "CheckUserToRegister",
			Handler:    _GigxRRService_CheckUserToRegister_Handler,
		},
		{
			MethodName: "ResetUserPassword",
			Handler:    _GigxRRService_ResetUserPassword_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _GigxRRService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GigxRRService_DeleteUser_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _GigxRRService_SendEmail_Handler,
		},
		{
			MethodName: "GetIpInformation",
			Handler:    _GigxRRService_GetIpInformation_Handler,
		},
		{
			MethodName: "CheckVerificationLink",
			Handler:    _GigxRRService_CheckVerificationLink_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _GigxRRService_GetFile_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _GigxRRService_UpdateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _GigxRRService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllFiles",
			Handler:       _GigxRRService_GetAllFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gigxRR.proto",
}
